name: Platform Infrastructure CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'modules/**'
      - 'domains/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'modules/**'
      - 'domains/**'
      - '.github/workflows/**'

jobs:
  terraform-validate:
    name: 'Terraform Validation & Formatting'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.16.2

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init
      working-directory: ./domains/h1_gci_marketing

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./domains/h1_gci_marketing