name: Platform Infrastructure CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'modules/**'
      - 'domains/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'modules/**'
      - 'domains/**'
      - '.github/workflows/**'

jobs:
  terraform-validate:
    name: 'Terraform Validation'
    runs-on: ubuntu-latest

    # DYNAMIC MATRIX: Runs parallel jobs for each directory
    strategy:
      matrix:
        target_dir:
          - dev/h0_core_iam
          - dev/h1_gci_marketing
          - dev/h1_gci_sales
          # - prod/h0_core_iam
          - prod/h1_gci_marketing
          - prod/h1_gci_sales

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.16.2

    # Formatting is checked globally across the repo
    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    # Init uses the dynamic matrix path
    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: ./domains/${{ matrix.target_dir }}

    # Validate uses the dynamic matrix path
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./domains/${{ matrix.target_dir }}